on:
  workflow_dispatch:

jobs:
  create-zim:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: git checkout
      run: git checkout main      

    - name: install mwoffliner
      run: npm i -g mwoffliner

    - name: run mwoffliner
      run: mwoffliner --mwUrl=http://meta.miraheze.org/ --adminEmail=foo@bar.net --optimisationCacheUrl=""
